[
  {
    "id": 1,
    "name": "Name1",
    "description": "Description1",
    "angularDeveloperId": 1,
    "angularDeveloperName": "AngularDeveloperName1",
    "cSharpDeveloperId": 1,
    "cSharpDeveloperName": "CSharpDeveloperName1",
    "dbDeveloperId": 1,
    "dbDeveloperName": "DbDeveloperName1",
    "qaPersonId": 1,
    "qaPersonName": "QaPersonName1"
  },
  {
    "id": 2,
    "name": "Name2",
    "description": "Description2",
    "angularDeveloperId": 2,
    "angularDeveloperName": "AngularDeveloperName2",
    "cSharpDeveloperId": 2,
    "cSharpDeveloperName": "CSharpDeveloperName2",
    "dbDeveloperId": 2,
    "dbDeveloperName": "DbDeveloperName2",
    "qaPersonId": 2,
    "qaPersonName": "QaPersonName2"
  },
  {
    "id": 3,
    "name": "Name3",
    "description": "Description3",
    "angularDeveloperId": 3,
    "angularDeveloperName": "AngularDeveloperName3",
    "cSharpDeveloperId": 3,
    "cSharpDeveloperName": "CSharpDeveloperName3",
    "dbDeveloperId": 3,
    "dbDeveloperName": "DbDeveloperName3",
    "qaPersonId": 3,
    "qaPersonName": "QaPersonName3"
  },
  {
    "id": 4,
    "name": "Name4",
    "description": "Description4",
    "angularDeveloperId": 4,
    "angularDeveloperName": "AngularDeveloperName4",
    "cSharpDeveloperId": 4,
    "cSharpDeveloperName": "CSharpDeveloperName4",
    "dbDeveloperId": 4,
    "dbDeveloperName": "DbDeveloperName4",
    "qaPersonId": 4,
    "qaPersonName": "QaPersonName4"
  },
  {
    "id": 5,
    "name": "Name5",
    "description": "Description5",
    "angularDeveloperId": 5,
    "angularDeveloperName": "AngularDeveloperName5",
    "cSharpDeveloperId": 5,
    "cSharpDeveloperName": "CSharpDeveloperName5",
    "dbDeveloperId": 5,
    "dbDeveloperName": "DbDeveloperName5",
    "qaPersonId": 5,
    "qaPersonName": "QaPersonName5"
  },
  {
    "id": 6,
    "name": "Name6",
    "description": "Description6",
    "angularDeveloperId": 6,
    "angularDeveloperName": "AngularDeveloperName6",
    "cSharpDeveloperId": 6,
    "cSharpDeveloperName": "CSharpDeveloperName6",
    "dbDeveloperId": 6,
    "dbDeveloperName": "DbDeveloperName6",
    "qaPersonId": 6,
    "qaPersonName": "QaPersonName6"
  },
  {
    "id": 7,
    "name": "Name7",
    "description": "Description7",
    "angularDeveloperId": 7,
    "angularDeveloperName": "AngularDeveloperName7",
    "cSharpDeveloperId": 7,
    "cSharpDeveloperName": "CSharpDeveloperName7",
    "dbDeveloperId": 7,
    "dbDeveloperName": "DbDeveloperName7",
    "qaPersonId": 7,
    "qaPersonName": "QaPersonName7"
  },
  {
    "id": 8,
    "name": "Name8",
    "description": "Description8",
    "angularDeveloperId": 8,
    "angularDeveloperName": "AngularDeveloperName8",
    "cSharpDeveloperId": 8,
    "cSharpDeveloperName": "CSharpDeveloperName8",
    "dbDeveloperId": 8,
    "dbDeveloperName": "DbDeveloperName8",
    "qaPersonId": 8,
    "qaPersonName": "QaPersonName8"
  },
  {
    "id": 9,
    "name": "Name9",
    "description": "Description9",
    "angularDeveloperId": 9,
    "angularDeveloperName": "AngularDeveloperName9",
    "cSharpDeveloperId": 9,
    "cSharpDeveloperName": "CSharpDeveloperName9",
    "dbDeveloperId": 9,
    "dbDeveloperName": "DbDeveloperName9",
    "qaPersonId": 9,
    "qaPersonName": "QaPersonName9"
  },
  {
    "id": 10,
    "name": "Name10",
    "description": "Description10",
    "angularDeveloperId": 10,
    "angularDeveloperName": "AngularDeveloperName10",
    "cSharpDeveloperId": 10,
    "cSharpDeveloperName": "CSharpDeveloperName10",
    "dbDeveloperId": 10,
    "dbDeveloperName": "DbDeveloperName10",
    "qaPersonId": 10,
    "qaPersonName": "QaPersonName10"
  }
]